### ISSUE TITLE
是否是深度学习方法

### ISSUE THREAD

**Issue by swjtulinxi** [xingchenzhang/VIFB#1]
你好，请问你的方法是否是基于深度学习的方法，如果是，是否可以用于其它类型数据，不只是可见光和红外，还有你的红外为啥也是3个波段呢？

**Comment by xingchenzhang** [comment]
你好，感谢评论。

我这个benchmark里收录的部分方法是基于深度学习的方法，具体可以参考论文。原则上方法可以用于其他数据类型，但是需要用其他类型的数据重新训练或者进行微调，直接使用的话效果估计会很差。

我观察到有些红外图像是单通道的，而有些是三通道的。没做专门处理。
