### ISSUE TITLE
Ground Truth

### ISSUE THREAD

**Issue by luoxiaodou** [xingchenzhang/VIFB#10]
Hello, is there a dataset of visible and infrared image pairs that has the ground truths of the fusion results for the supervised learning?

**Comment by xingchenzhang** [comment]
Hello,

No, unfortunately, this task does not have real ground truth. I know that some studies use existing fusion methods to generated fused results and see them as "ground truth" in supervised learning, but they are not real ground truth.

**Comment by luoxiaodou** [comment]
Thanks a lot, are these datasets including the generated fused ground truths public availably?

**Comment by luoxiaodou** [comment]
Thanks a lot, are these datasets including the generated fused ground truths publicly available?

**Comment by xingchenzhang** [comment]
To be honest, I am not sure. 

But you can check this. As far as I know, these papers are doing in this way:
1. Q. Li, L. Lu, Z. Li, W. Wu, Z. Liu, G. Jeon, and X. Yang, “Coupled GAN with relativistic discriminators for infrared and visible
images fusion,” IEEE Sensors Journal, vol. 21, no. 6, 2021
2. W.-B. An and H.-M. Wang, “Infrared and visible image fusion with supervised convolutional neural network,” Optik, vol. 219,
p. 165120, 2020

**Comment by luoxiaodou** [comment]
Many thanks.  Happy Mid-Autumn Festival!

**Comment by xingchenzhang** [comment]
Thanks! You too!
