### ISSUE TITLE
初次使用注意事项

### ISSUE THREAD

**Issue by taojianggit** [xingchenzhang/VIFB#11]
1.初次运行DLF和ResNet算法，除readme中提示的设置路径和下载模型外，可能还需要单独对MatConvNet进行初始化，如在...\matconvnet-1.0-beta25路径下，matlab命令窗口中运行`run matlab/vl_setupnn`;

2.初次运行MST_SR算法，可能还需要在...\methods\MST_SR\sparsefusion\ksvdbox\ompbox\private路径下，matlab命令窗口中运行`make`;

3.初次运行RP_SR算法，可能还需要在...\methods\RP_SR\sparsefusion\ksvdbox\ompbox\private路径下，matlab命令窗口中运行`make`;

4.初次运行NSCT_SR算法，可能还需要在...\methods\NSCT_SR\sparsefusion\ksvdbox\ompbox\private路径下，matlab命令窗口中运行`make`

**Comment by xingchenzhang** [comment]
Thank you for mentioning this! I will update the Readme later.
