### ISSUE TITLE
验证集问题

### ISSUE THREAD

**Issue by pengmy001** [xingchenzhang/VIFB#22]
你好！我看了你们的论文，VIFB是个非常有意义的工作。我看到在Quantitative performance comparison部分，没有提到各种融合方法的结果是与什么验证集进行的Quantitative Evaluation，是否可以说明一下，谢谢！

**Comment by xingchenzhang** [comment]
验证集？你的意思是我在什么数据集上进行的测试吗？我在VIFB的21对图像上进行的测试。VIFB中没有包含训练集
