### ISSUE TITLE
代码开源

### ISSUE THREAD

**Issue by guofenggitlearning** [xingchenzhang/VIFB#5]
您好，打算什么时候开源代码

**Comment by xingchenzhang** [comment]
您好！感谢评论。因为最近换了工作单位，加上英国疫情的原因，耽误了一些工作进度。代码我会整理一下，预计很快会开源

**Comment by xingchenzhang** [comment]
抱歉，更新迟了！

数据集、代码和图像融合结果均已更新。

谢谢！
