### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by lucienlgl** [xingchenzhang/VIFB#6]
你好，请问大概什么时间会开源代码呢，谢谢

**Comment by missyoudaisy** [comment]
同問

**Comment by PauloFavero** [comment]
Hi, Where can I get the open-source code?

**Comment by liujianghao1023** [comment]
同问

**Comment by choodly** [comment]
同问

**Comment by xingchenzhang** [comment]
迟复为谦！

数据集、代码和结果均已上传。

感谢关注！

**Comment by xingchenzhang** [comment]
> Hi, Where can I get the open-source code?

Hi,

Thank you for your interests!

Now the test set, code library and results are available. 

Regards,
Xingchen
