### ISSUE TITLE
why are there only 21 pairs of test image

### ISSUE THREAD

**Issue by ghost** [xingchenzhang/VIFB#9]
i mean, there tends to be a big dataset with lots of testing image.

**Comment by xingchenzhang** [comment]
Hi,

Thank you for your question.

As the first attempt to create a benchmark in the field of VIF, we only collected 21 pairs of visible and infrared images from different sources. In the future, we will extend it to contain more images. Also, if you have more image pairs, you can add them to this toolkit easily and obtain fusion results.

Bests,
Xingchen
